"""Final phase, Part 1 — localized fallback/limitation/off-topic responses.

Every fallback reply used to be shown in whatever language the admin
configured Settings.fallback_message/off_topic_message in (English, by
default) regardless of what language the question was asked in or explicitly
requested — the one part of a reply response_language.py's rules never
reached, since these messages are never generated by the model.

response_language.localize_fallback_message / localize_off_topic_message /
limitation_message close that gap: the *shipped default* text for each is
translated into every language this app already recognizes an explicit
request for (or, for Arabic, reliably identifies by script) — reusing
response_language.detect() as the sole source of truth, never a second
language-detection system. An admin's customized message, or a question in an
ambiguous/unsupported language, is shown exactly as before.

Most tests below trigger the fully deterministic "documented model, but not
this one" limitation path (zero LLM calls, same pattern as
test_applicability.test_model_without_matching_documentation_gets_a_limitation_reply)
so the exact reply text can be asserted without any model non-determinism."""

from app.rag import pipeline
from app.rag.response_language import ResponseLanguage, detect, limitation_message, localize_fallback_message, localize_off_topic_message
from tests.conftest import ANGLES, add_faq
from tests.conftest import angle as _angle
from tests.test_applicability import add_page

CUBE_PAGE_TITLE = "Cubos NB (localization fixture)"
CUBE_PAGE = "Cubos NB\nHeater Model | kW\nCUB3-45NB-P-C | 4.5\nStones: 20 kg"
CUBE_PAGE_URL = "https://www.sawo.com/cubos-nb-localization/"

BASE_Q = "How many kilograms of stones does the CUB3-45NS require?"
CUBE_NS_ANGLE = 400.0 + _angle(0.85)
ANGLES[CUBE_PAGE_TITLE] = 400.0

QUESTIONS = {
    "English": BASE_Q,
    "Finnish": f"{BASE_Q} Vastaa suomeksi.",
    "Swedish": f"{BASE_Q} Svara på svenska.",
    "German": f"{BASE_Q} Bitte antworte auf Deutsch.",
    # French/Spanish/Italian have no native trigger phrase in
    # response_language._NATIVE_REQUESTS (only Finnish/German/Swedish/Chinese
    # do) — the existing, unmodified detect() only recognizes an explicit
    # request for them via the English-verb pattern ("answer/reply/... in
    # <language>"), same as a real user typing the request in English.
    "French": f"{BASE_Q} Please answer in French.",
    "Spanish": f"{BASE_Q} Please answer in Spanish.",
    "Italian": f"{BASE_Q} Please answer in Italian.",
}
for _lang, _q in QUESTIONS.items():
    ANGLES[_q] = CUBE_NS_ANGLE

ARABIC_Q = "كم كجم من الحجارة يأخذ CUB3-45NS؟"
ANGLES[ARABIC_Q] = CUBE_NS_ANGLE

AMBIGUOUS_Q = "Wat is het gewicht van stenen in de CUB3-45NS?"  # Dutch, no explicit request marker
ANGLES[AMBIGUOUS_Q] = CUBE_NS_ANGLE


async def _limitation_reply(db, question: str):
    await add_page(db, CUBE_PAGE_TITLE, CUBE_PAGE, CUBE_PAGE_URL)
    return await pipeline.answer_question(db, question, session_id=f"s-{hash(question)}")


# --- Tests 1-7: one language each, through the real pipeline -----------------------------


async def test_english_fallback(db, embedder, llm):
    result = await _limitation_reply(db, QUESTIONS["English"])
    assert result.is_fallback and "CUB3-45NS" in result.answer
    assert "doesn't establish an answer" in result.answer  # default English wording, untranslated


async def test_finnish_fallback(db, embedder, llm):
    result = await _limitation_reply(db, QUESTIONS["Finnish"])
    assert result.is_fallback and "CUB3-45NS" in result.answer
    assert "ei anna vastausta" in result.answer
    assert "doesn't establish" not in result.answer


async def test_swedish_fallback(db, embedder, llm):
    result = await _limitation_reply(db, QUESTIONS["Swedish"])
    assert result.is_fallback and "CUB3-45NS" in result.answer
    assert "inte något svar" in result.answer


async def test_german_fallback(db, embedder, llm):
    result = await _limitation_reply(db, QUESTIONS["German"])
    assert result.is_fallback and "CUB3-45NS" in result.answer
    assert "keine Antwort" in result.answer


async def test_french_fallback(db, embedder, llm):
    result = await _limitation_reply(db, QUESTIONS["French"])
    assert result.is_fallback and "CUB3-45NS" in result.answer
    assert "ne permet pas de répondre" in result.answer


async def test_spanish_fallback(db, embedder, llm):
    result = await _limitation_reply(db, QUESTIONS["Spanish"])
    assert result.is_fallback and "CUB3-45NS" in result.answer
    assert "no ofrece una respuesta" in result.answer


async def test_italian_fallback(db, embedder, llm):
    result = await _limitation_reply(db, QUESTIONS["Italian"])
    assert result.is_fallback and "CUB3-45NS" in result.answer
    assert "non fornisce una risposta" in result.answer


async def test_arabic_fallback(db, embedder, llm):
    result = await _limitation_reply(db, ARABIC_Q)
    assert result.is_fallback and "CUB3-45NS" in result.answer
    assert "لا توثّق الوثائق المتاحة" in result.answer


# --- Test 8: explicit language request is honored -----------------------------------------


def test_explicit_language_request_selects_the_requested_translation():
    language = detect("Please answer in Finnish.")
    assert language.name == "Finnish" and language.explicit
    localized = localize_fallback_message(
        "Thanks for your question, we've taken note of it and will follow up once we have an answer.", language
    )
    assert localized.startswith("Kiitos kysymyksestäsi")


# --- Test 9: ambiguous language keeps the existing safe default ---------------------------


async def test_ambiguous_language_keeps_the_english_default(db, embedder, llm):
    language = detect(AMBIGUOUS_Q)
    assert language.name is None and language.script == "latin"  # Dutch is not implicitly named — by design

    result = await _limitation_reply(db, AMBIGUOUS_Q)
    assert result.is_fallback and "doesn't establish an answer" in result.answer  # unchanged, safe default


def test_customized_message_is_never_auto_translated():
    language = ResponseLanguage(name="Finnish", script="latin", explicit=True)
    custom = "Please contact support@example.com for help with this."
    assert localize_fallback_message(custom, language) == custom  # not the shipped default -> untouched


# --- Test 10: technical identifiers are preserved in every language ----------------------


async def test_technical_identifiers_survive_localization(db, embedder, llm):
    for question in (QUESTIONS["Finnish"], QUESTIONS["German"], ARABIC_Q):
        result = await _limitation_reply(db, question)
        assert "CUB3-45NS" in result.answer  # model code copied verbatim, never translated


def test_limitation_message_never_translates_technical_identifiers():
    language = ResponseLanguage(name="French", script="latin", explicit=True)
    message = limitation_message("SW3-45NS", ["NB", "STE"], language)
    assert "SW3-45NS" in message and "NB" in message and "STE" in message
    assert "ne permet pas de répondre" in message


# --- off-topic localization (unit-level: see test_response_language.py for the -----------
# --- LLM-generated off-topic reply path, which this phase does not change) ---------------


def test_off_topic_message_is_localized_for_a_supported_language():
    language = ResponseLanguage(name="German", script="latin", explicit=True)
    localized = localize_off_topic_message(
        "I'm here to help with product and technical support questions — what can I help you with?", language
    )
    assert "womit kann ich helfen" in localized


def test_off_topic_message_falls_back_to_default_for_unsupported_language():
    language = ResponseLanguage(name=None, script="latin", explicit=False)
    message = "I'm here to help with product and technical support questions — what can I help you with?"
    assert localize_off_topic_message(message, language) == message
