"""Which language an answer must be written in, and whether it was.

No prompt said anything about language, so the answer's language was left to
the model. The configured chat model (deepseek-v4-flash) was trained heavily
on Chinese, and with nothing anchoring it an English warranty question came
back in Chinese — including, when it had nothing to say, a Chinese "sorry,
not found" in place of the NOT_FOUND sentinel. That reply is neither the
sentinel nor checked by the fact-check (skipped for Library contexts), so it
reached the user as-is.

The rule, applied to every generated reply:
  * answer in the language the user explicitly asked for, if they did;
  * otherwise in the language of the question — never of the retrieved
    excerpts or of earlier turns;
  * product names, model numbers, error codes and measurements are copied, not
    translated.
The language is established from the question text itself (script, plus
English function words for Latin-script text), so no extra AI call is made.
A generated reply in the wrong writing system is rejected afterwards
(answer_matches), because the prompt alone is exactly what failed.

Fallback/limitation/off-topic replies are a separate case: they are never
generated by the model (or, for off-topic, fall back to a fixed string when
generation fails), so the rule above can't apply a language instruction to
them the way it does for a real answer. localize_fallback_message,
localize_off_topic_message and limitation_message below cover that: the
*shipped default* wording for each is translated into every language this
module can already name or reliably identify by script — never an admin's own
customized text, which there is no safe way to auto-translate, and never a
language this module can only call "the language of the question" (ambiguous
Latin-script text, or a script that spans several real languages) — that case
keeps today's behavior, the message exactly as configured.
"""

import re
from dataclasses import dataclass

from app.core.config import settings

# Unicode letter ranges per writing system. Only the scripts a reply could
# plausibly drift into need to be here; anything unlisted counts as neither.
_SCRIPT_RANGES = {
    "latin": ((0x41, 0x5A), (0x61, 0x7A), (0xC0, 0x24F)),
    "han": ((0x3400, 0x4DBF), (0x4E00, 0x9FFF), (0xF900, 0xFAFF)),
    "kana": ((0x3040, 0x30FF),),
    "hangul": ((0x1100, 0x11FF), (0xAC00, 0xD7AF)),
    "cyrillic": ((0x400, 0x4FF),),
    "greek": ((0x370, 0x3FF),),
    "arabic": ((0x600, 0x6FF),),
    "hebrew": ((0x590, 0x5FF),),
    "thai": ((0xE00, 0xE7F),),
}

# Script a question is written in -> the language to name in the prompt, when
# the script alone settles it (Cyrillic, Arabic, ... do not, and are left as
# "the language of the question").
_SCRIPT_LANGUAGE = {"han": "Chinese", "kana": "Japanese", "hangul": "Korean", "greek": "Greek", "thai": "Thai", "hebrew": "Hebrew"}

# Languages a user can ask for by name -> (prompt name, script).
_NAMED_LANGUAGES = {
    "english": ("English", "latin"),
    "chinese": ("Chinese", "han"),
    "mandarin": ("Chinese", "han"),
    "finnish": ("Finnish", "latin"),
    "swedish": ("Swedish", "latin"),
    "german": ("German", "latin"),
    "french": ("French", "latin"),
    "spanish": ("Spanish", "latin"),
    "italian": ("Italian", "latin"),
    "dutch": ("Dutch", "latin"),
    "estonian": ("Estonian", "latin"),
    "polish": ("Polish", "latin"),
    "portuguese": ("Portuguese", "latin"),
    "russian": ("Russian", "cyrillic"),
    "japanese": ("Japanese", "kana"),
    "korean": ("Korean", "hangul"),
}
_LANG_ALT = "|".join(_NAMED_LANGUAGES)

# "answer in Chinese", "please reply in simplified Chinese", "translate it into
# Finnish", "in German please". A bare "in Finnish" is not enough — "what is
# it called in Finnish?" asks for a word, and "tell me if the manual is
# available in Chinese" asks about a manual — so only a few filler words may
# sit between the verb and the language.
_REQUEST_FILLER = r"(?:\s+(?:it|this|that|me|us|them|back|everything|all|the answer|your answer|the reply|your reply))*"
_REQUEST_RES = (
    re.compile(
        rf"\b(?:answer|reply|respond|write|explain|translate|say|tell me|describe)\b{_REQUEST_FILLER}"
        rf"\s+(?:in|into)\s+(?:simplified\s+|traditional\s+)?({_LANG_ALT})\b",
        re.I,
    ),
    re.compile(rf"\b(?:in|into)\s+(?:simplified\s+|traditional\s+)?({_LANG_ALT})\s*,?\s*(?:please|pls)\b", re.I),
    re.compile(rf"\b(?:please|pls)\s*,?\s*(?:in|into)\s+(?:simplified\s+|traditional\s+)?({_LANG_ALT})\b", re.I),
)
# Requests written in the language itself.
_NATIVE_REQUESTS = (
    (re.compile(r"用中文|中文回答|中文回复|请用中文"), ("Chinese", "han")),
    (re.compile(r"\bauf deutsch\b", re.I), ("German", "latin")),
    (re.compile(r"\bsuomeksi\b", re.I), ("Finnish", "latin")),
    (re.compile(r"\bpå svenska\b", re.I), ("Swedish", "latin")),
    (re.compile(r"\bin english\b", re.I), ("English", "latin")),
)

# Words that mark Latin-script text as English. Two distinct ones are
# required, and words other languages share ("in", "die", "a") are left out, so
# "wat is de garantie" or "Was ist die Garantie" is not taken for English.
_ENGLISH_WORDS = frozenset(
    "the what how why which does doesn't don't is isn't are aren't my can can't could should would "
    "when where who there this that these with and for of to it its won't not please you your "
    "have has we our any".split()
)
_WORD_RE = re.compile(r"[a-z']+")

# A reply is "in the wrong writing system" when this share of its letters is
# foreign to the expected one. Model codes and units are Latin inside any
# language, so a Chinese reply is still mostly Han, and an English reply
# quoting one foreign term stays well below it.
_FOREIGN_SHARE_LIMIT = 0.2


@dataclass(frozen=True)
class ResponseLanguage:
    name: str | None  # "English", "Chinese"; None = mirror the question
    script: str  # writing system the reply must be in
    explicit: bool = False  # the user asked for it

    def reply_rule(self) -> str:
        if self.name and self.explicit:
            target = f"in {self.name}, as the user asked"
        elif self.name:
            target = f"in {self.name}, the language of the user's message"
        else:
            target = "in the same language as the user's message"
        return f"Write your entire reply {target}."

    def instruction(self) -> str:
        """reply_rule plus the rules for answers written from context."""
        return (
            f"{self.reply_rule()} The context excerpts and earlier conversation turns may be "
            "in other languages; their language never decides the language of your reply, so translate "
            "whatever you use from them. Copy product names, model numbers, error and display codes, part "
            "designators, measurements and units exactly as written in the context; never translate or "
            "alter them. If you cannot answer, reply with the exact sentinel you were given, not with an "
            "apology in any language."
        )


def _script_counts(text: str) -> dict[str, int]:
    counts: dict[str, int] = {}
    for char in text:
        code = ord(char)
        for script, ranges in _SCRIPT_RANGES.items():
            if any(lo <= code <= hi for lo, hi in ranges):
                counts[script] = counts.get(script, 0) + 1
                break
    return counts


def _dominant_script(text: str) -> str:
    counts = _script_counts(text)
    # Model codes are Latin inside a question in any language, and one Han
    # character carries a whole word, so any real run of a non-Latin script
    # decides it.
    non_latin = {s: n for s, n in counts.items() if s != "latin"}
    if non_latin:
        script, n = max(non_latin.items(), key=lambda item: item[1])
        if n >= 2 or not counts.get("latin"):
            return "kana" if script == "han" and counts.get("kana") else script
    return "latin"


def detect(question: str) -> ResponseLanguage:
    for pattern in _REQUEST_RES:
        match = pattern.search(question)
        if match:
            name, script = _NAMED_LANGUAGES[match.group(1).lower()]
            return ResponseLanguage(name, script, explicit=True)
    for pattern, (name, script) in _NATIVE_REQUESTS:
        if pattern.search(question):
            return ResponseLanguage(name, script, explicit=True)

    script = _dominant_script(question)
    if script != "latin":
        return ResponseLanguage(_SCRIPT_LANGUAGE.get(script), script)
    words = set(_WORD_RE.findall(question.lower().replace("’", "'")))
    if len(words & _ENGLISH_WORDS) >= 2:
        return ResponseLanguage("English", "latin")
    return ResponseLanguage(None, "latin")


def answer_matches(answer: str, language: ResponseLanguage) -> bool:
    """False when the reply is written in a different writing system than the
    one required — e.g. Chinese for an English question. Same-script mixups
    (Finnish for English) can't be told apart this cheaply and are left to
    the prompt."""
    counts = _script_counts(answer)
    total = sum(counts.values())
    if not total:
        return True
    expected = counts.get(language.script, 0)
    if language.script == "kana":  # Japanese is written with Han and kana together
        expected += counts.get("han", 0)
    if language.script == "latin":
        return (total - expected) / total <= _FOREIGN_SHARE_LIMIT
    return expected / total >= _FOREIGN_SHARE_LIMIT


# --- localized fallback / limitation / off-topic text ------------------------------------

# A script this module can read as clearly one specific language even though
# _SCRIPT_LANGUAGE (above) deliberately does not: a Latin-script or Cyrillic
# reply's language is names-only, decided by explicit request or nothing at
# all, because those scripts are shared by too many unrelated languages
# to name one from the script alone. Arabic script is technically shared too
# (Persian, Urdu, ...), but this only ever *selects canned text*, never
# asserts a language for the model to write in (that instruction, in
# _generation_prompt/reply_rule, is untouched) — a Farsi or Urdu reader still
# gets a fallback in their own writing system rather than in English, which is
# strictly better even when the exact language name is not.
_SCRIPT_ONLY_LANGUAGE_NAME = {"arabic": "Arabic"}


def _translation_key(language: ResponseLanguage) -> str | None:
    return language.name or _SCRIPT_ONLY_LANGUAGE_NAME.get(language.script)


def _localize_default(message: str, default: str, translations: dict[str, str], language: ResponseLanguage) -> str:
    """`message` translated into `language`, but ONLY when it is still
    exactly the shipped default — an admin who customized the fallback/
    off-topic text in Settings sees exactly what they configured, in
    whatever language they wrote it, since there is no safe way to
    auto-translate arbitrary staff-authored text. Ambiguous or
    unsupported languages return `message` unchanged too: the existing safe
    default, never a guess."""
    if message != default:
        return message
    key = _translation_key(language)
    if key is None:
        return message
    return translations.get(key, message)


# Every language _NAMED_LANGUAGES already recognizes an explicit "answer in
# X" request for, plus Arabic (script-detected, see _SCRIPT_ONLY_LANGUAGE_NAME
# above) — the same set this Helpdesk already claims to support elsewhere in
# this module. Keyed on the exact default string from app.core.config so a
# customized message never matches and is left untouched (see
# _localize_default).
_FALLBACK_TRANSLATIONS: dict[str, str] = {
    "English": settings.default_fallback_message,
    "Finnish": "Kiitos kysymyksestäsi — olemme kirjanneet sen ylös ja palaamme asiaan, kun meillä on vastaus.",
    "Swedish": "Tack för din fråga — vi har noterat den och återkommer när vi har ett svar.",
    "German": "Danke für Ihre Frage — wir haben sie notiert und melden uns, sobald wir eine Antwort haben.",
    "French": "Merci pour votre question — nous l'avons notée et reviendrons vers vous dès que nous aurons une réponse.",
    "Spanish": "Gracias por tu pregunta. La hemos registrado y te responderemos en cuanto tengamos una respuesta.",
    "Italian": "Grazie per la tua domanda: l'abbiamo registrata e ti risponderemo non appena avremo una risposta.",
    "Dutch": "Bedankt voor je vraag — we hebben deze genoteerd en komen erop terug zodra we een antwoord hebben.",
    "Estonian": "Täname küsimuse eest — oleme selle üles märkinud ja anname vastuse niipea kui võimalik.",
    "Polish": "Dziękujemy za pytanie — odnotowaliśmy je i odpowiemy, gdy tylko będziemy mieli odpowiedź.",
    "Portuguese": "Obrigado pela sua pergunta — registámo-la e responderemos assim que tivermos uma resposta.",
    "Russian": "Спасибо за ваш вопрос — мы его зафиксировали и ответим, как только у нас будет ответ.",
    "Chinese": "感谢您的提问——我们已记录，一有答案会尽快回复您。",
    "Japanese": "ご質問ありがとうございます。内容を記録しましたので、回答が用意でき次第ご連絡します。",
    "Korean": "문의해 주셔서 감사합니다 — 내용을 기록했으며, 답변이 준비되는 대로 안내드리겠습니다.",
    "Arabic": "شكرًا على سؤالك — لقد سجّلنا استفسارك وسنعاود التواصل بمجرد توفر إجابة.",
}

_OFF_TOPIC_TRANSLATIONS: dict[str, str] = {
    "English": settings.default_off_topic_message,
    "Finnish": "Olen täällä auttaakseni tuote- ja teknisissä tukikysymyksissä — missä voin auttaa?",
    "Swedish": "Jag finns här för att hjälpa till med produkt- och supportfrågor — vad kan jag hjälpa dig med?",
    "German": "Ich bin hier, um bei Produkt- und technischen Support-Fragen zu helfen — womit kann ich helfen?",
    "French": "Je suis là pour vous aider avec des questions produit ou d'assistance technique — que puis-je faire pour vous ?",
    "Spanish": "Estoy aquí para ayudarte con preguntas de producto o soporte técnico. ¿En qué puedo ayudarte?",
    "Italian": "Sono qui per aiutarti con domande su prodotti o assistenza tecnica: come posso aiutarti?",
    "Dutch": "Ik ben er om te helpen met product- en technische ondersteuningsvragen — waarmee kan ik helpen?",
    "Estonian": "Olen siin, et aidata toote- ja tehniliste tugiküsimustega — kuidas saan aidata?",
    "Polish": "Jestem tu, aby pomóc w kwestiach dotyczących produktu i wsparcia technicznego — w czym mogę pomóc?",
    "Portuguese": "Estou aqui para ajudar com questões de produto e suporte técnico — em que posso ajudar?",
    "Russian": "Я здесь, чтобы помочь с вопросами о продукте и технической поддержке — чем могу помочь?",
    "Chinese": "我在这里为您解答产品和技术支持方面的问题——请问有什么可以帮您？",
    "Japanese": "製品やテクニカルサポートに関するご質問にお答えします。どのようなご用件でしょうか？",
    "Korean": "제품 및 기술 지원 관련 문의를 도와드리고 있습니다 — 무엇을 도와드릴까요?",
    "Arabic": "أنا هنا للمساعدة في أسئلة المنتج والدعم الفني — كيف يمكنني مساعدتك؟",
}

# The two English sentence fragments pipeline._limitation_message composes
# ("no excerpt establishes an answer for this model" and, when something
# else was found instead, "here's what that unrelated material covers"),
# translated the same way as the fixed strings above. {target}/{others} are
# technical identifiers (model/product names) substituted in, never
# translated — see technical_key.py / applicability.Scope.describe.
_LIMITATION_INTRO_TEMPLATES: dict[str, str] = {
    "English": "The available documentation doesn't establish an answer to this for {target}.",
    "Finnish": "Saatavilla oleva dokumentaatio ei anna vastausta tähän kysymykseen kohteelle {target}.",
    "Swedish": "Den tillgängliga dokumentationen ger inte något svar på detta för {target}.",
    "German": "Die verfügbare Dokumentation liefert dafür keine Antwort für {target}.",
    "French": "La documentation disponible ne permet pas de répondre à cette question pour {target}.",
    "Spanish": "La documentación disponible no ofrece una respuesta a esto para {target}.",
    "Italian": "La documentazione disponibile non fornisce una risposta a questo per {target}.",
    "Dutch": "De beschikbare documentatie geeft hier geen antwoord op voor {target}.",
    "Estonian": "Saadaolev dokumentatsioon ei anna sellele vastust seadme {target} kohta.",
    "Polish": "Dostępna dokumentacja nie zawiera odpowiedzi na to dla {target}.",
    "Portuguese": "A documentação disponível não estabelece uma resposta a isto para {target}.",
    "Russian": "Доступная документация не содержит ответа на этот вопрос для {target}.",
    "Chinese": "现有文档中没有关于 {target} 的相关答案。",
    "Japanese": "現在のドキュメントには、{target} についてのこの質問への回答が見つかりません。",
    "Korean": "현재 문서에는 {target}에 대한 이 질문의 답변이 없습니다.",
    "Arabic": "لا توثّق الوثائق المتاحة إجابة على هذا بخصوص {target}.",
}
_LIMITATION_OTHERS_TEMPLATES: dict[str, str] = {
    "English": (
        " The related material found is for {others}, and nothing in it says it also "
        "applies to {target}, so it has not been applied here."
    ),
    "Finnish": (
        " Löydetty aiheeseen liittyvä materiaali koskee kohdetta {others}, eikä siinä sanota "
        "sen koskevan myös kohdetta {target}, joten sitä ei ole käytetty tässä."
    ),
    "Swedish": (
        " Det relaterade material som hittades gäller {others}, och inget i det säger att det "
        "även gäller {target}, så det har inte använts här."
    ),
    "German": (
        " Das gefundene verwandte Material bezieht sich auf {others}, und nichts darin besagt, "
        "dass es auch für {target} gilt, daher wurde es hier nicht verwendet."
    ),
    "French": (
        " Le contenu associé trouvé concerne {others}, et rien n'indique qu'il s'applique "
        "aussi à {target}, il n'a donc pas été utilisé ici."
    ),
    "Spanish": (
        " El material relacionado encontrado es para {others}, y nada en él indica que también "
        "se aplique a {target}, por lo que no se ha utilizado aquí."
    ),
    "Italian": (
        " Il materiale correlato trovato riguarda {others} e nulla indica che si applichi "
        "anche a {target}, quindi non è stato utilizzato qui."
    ),
    "Dutch": (
        " Het gevonden gerelateerde materiaal gaat over {others}, en nergens staat dat dit ook "
        "geldt voor {target}, dus het is hier niet gebruikt."
    ),
    "Estonian": (
        " Leitud seotud materjal käsitleb seadet {others} ning miski selles ei viita, et see "
        "kehtiks ka seadme {target} kohta, seega seda siin ei kasutatud."
    ),
    "Polish": (
        " Znaleziony powiązany materiał dotyczy {others} i nic w nim nie wskazuje, że dotyczy "
        "również {target}, więc nie został tu zastosowany."
    ),
    "Portuguese": (
        " O material relacionado encontrado é sobre {others}, e nada nele diz que também se "
        "aplica a {target}, por isso não foi utilizado aqui."
    ),
    "Russian": (
        " Найденные связанные материалы относятся к {others}, и ничто в них не указывает, что "
        "это также применимо к {target}, поэтому они здесь не использованы."
    ),
    "Chinese": "找到的相关内容是关于 {others} 的，其中并未说明也适用于 {target}，因此未在此采用。",
    "Japanese": "見つかった関連情報は {others} に関するもので、{target} にも当てはまるとは記載されていないため、ここでは使用していません。",
    "Korean": "발견된 관련 자료는 {others}에 관한 것이며, {target}에도 적용된다는 내용은 없으므로 여기서는 사용하지 않았습니다.",
    "Arabic": " المادة ذات الصلة التي تم العثور عليها تخص {others}، ولا يوجد ما يشير إلى أنها تنطبق أيضًا على {target}، لذلك لم يتم استخدامها هنا.",
}


def localize_fallback_message(message: str, language: ResponseLanguage) -> str:
    """The generic "we've noted your question" fallback, in the user's
    explicitly-requested or reliably-detected language — see
    _localize_default for exactly when that applies."""
    return _localize_default(message, settings.default_fallback_message, _FALLBACK_TRANSLATIONS, language)


def localize_off_topic_message(message: str, language: ResponseLanguage) -> str:
    """The off-topic redirect shown when a small-talk reply couldn't be
    generated (or the generated one failed its own language check) — see
    _localize_default for exactly when translation applies."""
    return _localize_default(message, settings.default_off_topic_message, _OFF_TOPIC_TRANSLATIONS, language)


def limitation_message(target: str, others: list[str], language: ResponseLanguage) -> str:
    """pipeline._limitation_message's lead-in sentence(s), localized.
    `target` (the model/product the question named) and `others` (what
    unrelated documentation was found instead) are technical identifiers,
    substituted in as-is and never translated."""
    key = _translation_key(language) or "English"
    intro = _LIMITATION_INTRO_TEMPLATES.get(key, _LIMITATION_INTRO_TEMPLATES["English"]).format(target=target)
    if not others:
        return intro
    others_template = _LIMITATION_OTHERS_TEMPLATES.get(key, _LIMITATION_OTHERS_TEMPLATES["English"])
    return intro + others_template.format(others=", ".join(others), target=target)
