OPENROUTER_API_KEY = "openrouter_api_key"
OPENROUTER_MODEL = "openrouter_model"
OPENROUTER_EMBEDDING_MODEL = "openrouter_embedding_model"
FALLBACK_MESSAGE = "fallback_message"
CONFIDENCE_THRESHOLD = "confidence_threshold"
TOP_K = "top_k"
OFF_TOPIC_THRESHOLD = "off_topic_threshold"
OFF_TOPIC_MESSAGE = "off_topic_message"
MAX_SITEMAP_URLS = "max_sitemap_urls"

ADMIN_ONLY_KEYS = {
    OPENROUTER_API_KEY,
    OPENROUTER_MODEL,
    OPENROUTER_EMBEDDING_MODEL,
}

MASKED_KEYS = {OPENROUTER_API_KEY}

ALL_KEYS = {
    OPENROUTER_API_KEY,
    OPENROUTER_MODEL,
    OPENROUTER_EMBEDDING_MODEL,
    FALLBACK_MESSAGE,
    CONFIDENCE_THRESHOLD,
    TOP_K,
    OFF_TOPIC_THRESHOLD,
    OFF_TOPIC_MESSAGE,
    MAX_SITEMAP_URLS,
}
