AI_ENGINE = "ai_engine"
OPENROUTER_API_KEY = "openrouter_api_key"
OPENROUTER_MODEL = "openrouter_model"
OLLAMA_BASE_URL = "ollama_base_url"
OLLAMA_GENERATION_MODEL = "ollama_generation_model"
OLLAMA_EMBEDDING_MODEL = "ollama_embedding_model"
OLLAMA_VISION_MODEL = "ollama_vision_model"
FALLBACK_MESSAGE = "fallback_message"
CONFIDENCE_THRESHOLD = "confidence_threshold"
TOP_K = "top_k"
OFF_TOPIC_THRESHOLD = "off_topic_threshold"
OFF_TOPIC_MESSAGE = "off_topic_message"

ADMIN_ONLY_KEYS = {
    AI_ENGINE,
    OPENROUTER_API_KEY,
    OPENROUTER_MODEL,
    OLLAMA_BASE_URL,
    OLLAMA_GENERATION_MODEL,
    OLLAMA_EMBEDDING_MODEL,
    OLLAMA_VISION_MODEL,
}

MASKED_KEYS = {OPENROUTER_API_KEY}

ALL_KEYS = {
    AI_ENGINE,
    OPENROUTER_API_KEY,
    OPENROUTER_MODEL,
    OLLAMA_BASE_URL,
    OLLAMA_GENERATION_MODEL,
    OLLAMA_EMBEDDING_MODEL,
    OLLAMA_VISION_MODEL,
    FALLBACK_MESSAGE,
    CONFIDENCE_THRESHOLD,
    TOP_K,
    OFF_TOPIC_THRESHOLD,
    OFF_TOPIC_MESSAGE,
}
